### ISSUE TITLE
local variable 'pp' referenced before assignment

### ISSUE THREAD

**Issue by muraatozbek** [harfang3d/game-dogfight#10]
Getting error when running the main.py and when i click "space" it gives error
 any solution for that?

 File "main.py", line 1477, in <module>
    game_phase = game_phase(plus, delta_t)
  File "main.py", line 1284, in main_phase
    Main.p1_aircraft.stabilize(dts, pk & pp, yk & yp, rk & rp)
UnboundLocalError: local variable 'pp' referenced before assignment

**Comment by astrofra** [comment]
Hi,

it seems there is a missing `else`, in case no gamepad is plugged on the computer.
Could you try this fix and tell me if it works : 

```python
    pk, rk, yk = control_aircraft_keyboard(dts, Main.p1_aircraft)
    if Main.controller is not None:
        pp, rp, yp = control_aircraft_paddle(dts, Main.p1_aircraft)
    else:
        pp, rp, yp = True, True, True

    Main.p1_aircraft.stabilize(dts, pk & pp, yk & yp, rk & rp)
```

**Comment by muraatozbek** [comment]
Thanks, it worked properly :)

**Comment by astrofra** [comment]
OK, Great. Feel free to submit a pull request including this fix.
