### ISSUE TITLE
liblua53.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by muraatozbek** [harfang3d/game-dogfight#9]
Getting error when run the main.py
How can i solve it?
   import harfang as hg
  File "/home/ozbek/.local/lib/python3.5/site-packages/harfang/__init__.py", line 1, in <module>
    from .harfang import *
ImportError: liblua53.so: cannot open shared object file: No such file or directory

**Comment by cudanexus** [comment]
Add liblua53.so from the `/home/ozbek/.local/lib/python3.5/site-packages/harfang/` folder to `/usr/local/lib`
here is the step to do that go to below directory  
`sudo cp /home/ozbek/.local/lib/python3.5/site-packages/harfang/liblua53.so /usr/local/lib/liblua53.so`
 and run `sudo ldconfig` this will solve your issue.

**Comment by astrofra** [comment]
Thanks for the help, @cudanexus :)
